appunti su binomiale, tre carte ed Ehrenfest, teoria su binomiale, action md to pdf
unipr-org/MSN pull request #2
Opened 2024-12-01 11:46 UTC by RossoMalpelooo

aggiunta github action che converte markdown in pdf per avere una visualizzazione corretta. Da sistemare il percorso in cui vengono memorizzati i file convertiti.

2024-12-10 06:12 UTC, manueldiagostino requested changes

2024-12-10 06:12 UTC, manueldiagostino commented on .github/workflows/md-to-pdf.yml
Prova a utilizzare l'action già implementata nelle altre repo (ad es. https://github.com/unipr-org/LIeC/blob/main/.github%2Fworkflows%2Fconvert-to-html.yml)

2025-02-05 15:42 UTC, manueldiagostino approved these changes

2025-02-05 15:43 UTC, simonecolli approved these changes

2025-02-05 15:43 UTC, merged